[package]
name = "rrconfig"
authors = ["ETH Zurich"]
license = "MPL-2.0"

edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
config.workspace = true
path-clean.workspace = true
serde.workspace = true
