[package]
name = "rrconfig"
authors = ["The RefinedRust Developers and Contributors"]
license = "BSD-3-Clause"

edition.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
config.workspace = true
serde.workspace = true
toml.workspace = true
