dump_borrowck_info=true
output_dir="./output"
log_dir = "./log"
run_check = false
extra_specs = "extra_specs.v"
lib_load_paths = ["../../stdlib"]
generate_dune_project = false
post_generation_hook = "patch output/minivec/generated/generated_code_minivec.v annotation_patch.patch"
