output_dir = "output"
lib_load_paths = ["../../stdlib"]
extra_specs = "extra_specs.v"
dump_borrowck_info = true
log_dir = "log"
post_generation_hook = "patch output/minivec/generated/generated_code_minivec.v annotation_patch.patch"
