[package]
name = "analysis_driver"
version = "0.1.0"
edition = "2024"

authors = ["Federico Poli <federpoli@gmail.com>"]
license = "MPL-2.0"

[dependencies]
analysis.path = "../.."
rr_rustc_interface.path = "../../../rr_rustc_interface"

env_logger = "0.11"
serde_json = "1"

[workspace]
