[build]
rustflags = [
    # === ENABLE ALL LINTS ===

    # Rust group lints
    "-Dfuture-incompatible",
    "-Dlet-underscore",
    "-Dnonstandard-style",
    "-Drefining-impl-trait",
    "-Drust-2018-idioms",
    "-Dunused",

    # Rust extra lints
    "-Dambiguous_negative_literals",
    "-Dclosure_returning_async_block",
    "-Dderef_into_dyn_supertrait",
    "-Dffi_unwind_calls",
    "-Dimpl_trait_redundant_captures",
    # "-Dlinker_messages",
    "-Dmacro_use_extern_crate",
    "-Dmeta_variable_misuse",
    "-Dmissing_copy_implementations",
    "-Dnon_ascii_idents",
    "-Dredundant_imports",
    "-Dredundant_lifetimes",
    "-Dsingle_use_lifetimes",
    "-Dtrivial_casts",
    "-Dtrivial_numeric_casts",
    "-Dunit_bindings",
    "-Dunnameable_types",
    "-Dunreachable_pub",
    "-Dunsafe_op_in_unsafe_fn",
    "-Dunused_import_braces",
    "-Dunused_lifetimes",
    "-Dunused_qualifications",

    # Clippy lints
    "-Dclippy::complexity",
    "-Dclippy::correctness",
    "-Dclippy::nursery",
    "-Dclippy::pedantic",
    "-Dclippy::perf",
    "-Dclippy::restriction",
    "-Dclippy::style",
    "-Dclippy::suspicious",

    # === DESIRABLE LINTS ===

    # clippy::correctness
    "-Aclippy::unused_io_amount",

    # clippy::nursery
    "-Aclippy::option_if_let_else",

    # clippy::restriction
    "-Aclippy::non_ascii_literal",
    "-Aclippy::panic_in_result_fn",
    "-Aclippy::unwrap_in_result",
    "-Aclippy::pub_use",

    # clippy::style
    "-Aclippy::new_without_default",
    "-Aclippy::write_with_newline",

    # === POTENTIAL LINTS (See: #7) ===

    # clippy::pedantic
    "-Aclippy::cast_possible_truncation",
    "-Aclippy::manual_assert",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
    "-Aclippy::uninlined_format_args",
    "-Aclippy::wildcard_imports",

    # clippy::restriction
    "-Aclippy::arithmetic_side_effects",
    "-Aclippy::as_conversions",
    "-Aclippy::clone_on_ref_ptr",
    "-Aclippy::exit",
    "-Aclippy::expect_used",
    "-Aclippy::field_scoped_visibility_modifiers",
    "-Aclippy::indexing_slicing",
    "-Aclippy::missing_assert_message",
    "-Aclippy::missing_asserts_for_indexing",
    "-Aclippy::missing_docs_in_private_items",
    "-Aclippy::panic",
    "-Aclippy::pattern_type_mismatch",
    "-Aclippy::print_stderr",
    "-Aclippy::print_stdout",
    "-Aclippy::string_slice",
    "-Aclippy::unimplemented",
    "-Aclippy::unwrap_used",
    "-Aclippy::use_debug",

    # === UNDESIRABLE LINTS ===

    # clippy::complexity
    "-Aclippy::too_many_arguments",
    "-Aclippy::type_complexity",

    # clippy::nursery
    "-Aclippy::cognitive_complexity",
    "-Aclippy::redundant_pub_crate",

    # clippy::pedantic
    "-Aclippy::implicit_hasher",
    "-Aclippy::many_single_char_names",
    "-Aclippy::match_wildcard_for_single_variants",
    "-Aclippy::too_many_lines",
    "-Aclippy::struct_field_names",

    # clippy::restriction
    "-Aclippy::allow_attributes_without_reason",
    "-Aclippy::arbitrary_source_item_ordering",
    "-Aclippy::default_numeric_fallback",
    "-Aclippy::else_if_without_else",
    "-Aclippy::exhaustive_enums",
    "-Aclippy::exhaustive_structs",
    "-Aclippy::format_push_string",
    "-Aclippy::implicit_return",
    "-Aclippy::integer_division",
    "-Aclippy::integer_division_remainder_used",
    "-Aclippy::iter_over_hash_type",
    "-Aclippy::min_ident_chars",
    "-Aclippy::missing_inline_in_public_items",
    "-Aclippy::missing_trait_methods",
    "-Aclippy::question_mark_used",
    "-Aclippy::return_and_then",
    "-Aclippy::shadow_reuse",
    "-Aclippy::shadow_same",
    "-Aclippy::shadow_unrelated",
    "-Aclippy::similar_names",
    "-Aclippy::single_call_fn",
    "-Aclippy::single_char_lifetime_names",
    "-Aclippy::std_instead_of_alloc",
    "-Aclippy::std_instead_of_core",
    "-Aclippy::unreachable",
    "-Aclippy::wildcard_enum_match_arm",

    # clippy::style
    "-Aclippy::just_underscores_and_digits",
    "-Aclippy::upper-case-acronyms",

    # clippy::suspicious
    "-Aclippy::duplicated_attributes",

    # === SPECIFIC LINTS ===

    # `clippy::restriction` is enabled globally, but used carefully.
    "-Aclippy::blanket_clippy_restriction_lints",

    "-Aclippy::mod_module_files", # see: self_named_module_files
    "-Aclippy::pub_with_shorthand", # see: pub_without_shortand
    "-Aclippy::semicolon_outside_block", # see: semicolon_inline_block
    "-Aclippy::separated_literal_suffix", # see: unseparated_literal_suffix
]
