[graph]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin"]
all-features = true

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "MPL-2.0", "Unicode-3.0"]

[bans]
multiple-versions = "deny"
